# Generated by Django 5.1.3 on 2025-02-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acc_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
