# Generated by Django 5.1.3 on 2025-02-02 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_alter_customuser_aadhar_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
